"""Independent Nasdaq TotalView-ITCH 5.0 synthetic byte builder.

This test-only module deliberately depends only on the Python standard library. It must not
import production reader or decoder code: the generated bytes are an independent oracle for
those later implementations.
"""

from __future__ import annotations

import gzip
import io
from collections import Counter
from dataclasses import dataclass
from typing import Final, Literal, TypeAlias

MessageType = Literal["S", "R", "H", "A", "F", "E", "C", "X", "D", "U", "P", "Q", "B"]
FieldValue: TypeAlias = int | str

NANOSECONDS_PER_DAY: Final = 86_400_000_000_000
MAX_FRAME_PAYLOAD: Final = 512
MESSAGE_TYPES: Final[tuple[MessageType, ...]] = (
    "S",
    "R",
    "H",
    "A",
    "F",
    "E",
    "C",
    "X",
    "D",
    "U",
    "P",
    "Q",
    "B",
)
MESSAGE_LENGTHS: Final[dict[MessageType, int]] = {
    "S": 12,
    "R": 39,
    "H": 25,
    "A": 36,
    "F": 40,
    "E": 31,
    "C": 36,
    "X": 23,
    "D": 19,
    "U": 35,
    "P": 44,
    "Q": 40,
    "B": 19,
}


class FixtureBuildError(ValueError):
    """Raised when a declarative fixture value cannot be encoded safely."""


@dataclass(frozen=True, slots=True)
class MessageDefinition:
    """One named synthetic ITCH message and its independent field values."""

    name: str
    message_type: MessageType
    fields: tuple[tuple[str, FieldValue], ...]

    def field_map(self) -> dict[str, FieldValue]:
        """Return a fresh field mapping for validation and encoding."""
        return dict(self.fields)


@dataclass(frozen=True, slots=True)
class BuiltMessage:
    """Encoded message with positions in its uncompressed framed stream."""

    definition: MessageDefinition
    payload: bytes
    message_index: int
    frame_offset: int
    payload_offset: int


@dataclass(frozen=True, slots=True)
class BuiltStream:
    """An immutable sequence of encoded messages and its framed bytes."""

    messages: tuple[BuiltMessage, ...]
    framed_bytes: bytes

    @property
    def counts_by_type(self) -> dict[str, int]:
        """Return deterministic message counts ordered by message type."""
        counts = Counter(message.definition.message_type for message in self.messages)
        return {
            message_type: counts[message_type]
            for message_type in MESSAGE_TYPES
            if counts[message_type] > 0
        }


def message(name: str, message_type: MessageType, **fields: FieldValue) -> MessageDefinition:
    """Create an immutable declarative message definition."""
    if not name or not name.isascii():
        raise FixtureBuildError("message name must be non-empty ASCII")
    if message_type not in MESSAGE_TYPES:
        raise FixtureBuildError(f"unsupported message type {message_type!r}")
    return MessageDefinition(name=name, message_type=message_type, fields=tuple(fields.items()))


def _require_fields(
    definition: MessageDefinition, required: tuple[str, ...]
) -> dict[str, FieldValue]:
    fields = definition.field_map()
    if len(fields) != len(definition.fields):
        raise FixtureBuildError(f"{definition.name}: duplicate field name")

    missing = sorted(set(required) - fields.keys())
    unknown = sorted(fields.keys() - set(required))
    if missing or unknown:
        details: list[str] = []
        if missing:
            details.append(f"missing {', '.join(missing)}")
        if unknown:
            details.append(f"unknown {', '.join(unknown)}")
        raise FixtureBuildError(f"{definition.name}: {'; '.join(details)}")
    return fields


def _unsigned(value: FieldValue, width: int, field_name: str) -> bytes:
    if isinstance(value, bool) or not isinstance(value, int):
        raise FixtureBuildError(f"{field_name} must be an integer")
    maximum = (1 << (width * 8)) - 1
    if value < 0 or value > maximum:
        raise FixtureBuildError(f"{field_name} must be in [0, {maximum}]")
    return value.to_bytes(width, byteorder="big", signed=False)


def _timestamp(value: FieldValue) -> bytes:
    if isinstance(value, bool) or not isinstance(value, int):
        raise FixtureBuildError("timestamp_ns must be an integer")
    if value < 0 or value >= NANOSECONDS_PER_DAY:
        raise FixtureBuildError(f"timestamp_ns must be in [0, {NANOSECONDS_PER_DAY - 1}]")
    return _unsigned(value, 6, "timestamp_ns")


def _alpha(value: FieldValue, width: int, field_name: str) -> bytes:
    if not isinstance(value, str):
        raise FixtureBuildError(f"{field_name} must be ASCII text")
    try:
        encoded = value.encode("ascii", errors="strict")
    except UnicodeEncodeError as error:
        raise FixtureBuildError(f"{field_name} must be ASCII text") from error
    if len(encoded) > width:
        raise FixtureBuildError(f"{field_name} must be at most {width} ASCII byte(s)")
    return encoded.ljust(width, b" ")


def _common(definition: MessageDefinition, fields: dict[str, FieldValue]) -> bytes:
    return (
        definition.message_type.encode("ascii")
        + _unsigned(fields["stock_locate"], 2, "stock_locate")
        + _unsigned(fields["tracking_number"], 2, "tracking_number")
        + _timestamp(fields["timestamp_ns"])
    )


def _encode_system_event(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition, ("stock_locate", "tracking_number", "timestamp_ns", "event_code")
    )
    return _common(definition, fields) + _alpha(fields["event_code"], 1, "event_code")


def _encode_stock_directory(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "stock",
            "market_category",
            "financial_status",
            "round_lot_size",
            "round_lots_only",
            "issue_classification",
            "issue_sub_type",
            "authenticity",
            "short_sale_threshold_indicator",
            "ipo_flag",
            "luld_reference_price_tier",
            "etp_flag",
            "etp_leverage_factor",
            "inverse_indicator",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _alpha(fields["stock"], 8, "stock"),
            _alpha(fields["market_category"], 1, "market_category"),
            _alpha(fields["financial_status"], 1, "financial_status"),
            _unsigned(fields["round_lot_size"], 4, "round_lot_size"),
            _alpha(fields["round_lots_only"], 1, "round_lots_only"),
            _alpha(fields["issue_classification"], 1, "issue_classification"),
            _alpha(fields["issue_sub_type"], 2, "issue_sub_type"),
            _alpha(fields["authenticity"], 1, "authenticity"),
            _alpha(
                fields["short_sale_threshold_indicator"],
                1,
                "short_sale_threshold_indicator",
            ),
            _alpha(fields["ipo_flag"], 1, "ipo_flag"),
            _alpha(fields["luld_reference_price_tier"], 1, "luld_reference_price_tier"),
            _alpha(fields["etp_flag"], 1, "etp_flag"),
            _unsigned(fields["etp_leverage_factor"], 4, "etp_leverage_factor"),
            _alpha(fields["inverse_indicator"], 1, "inverse_indicator"),
        )
    )


def _encode_trading_action(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "stock",
            "trading_state",
            "reserved",
            "reason",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _alpha(fields["stock"], 8, "stock"),
            _alpha(fields["trading_state"], 1, "trading_state"),
            _alpha(fields["reserved"], 1, "reserved"),
            _alpha(fields["reason"], 4, "reason"),
        )
    )


def _encode_add_order(definition: MessageDefinition, *, attributed: bool) -> bytes:
    required: tuple[str, ...] = (
        "stock_locate",
        "tracking_number",
        "timestamp_ns",
        "order_reference",
        "side",
        "shares",
        "stock",
        "price4",
    )
    if attributed:
        required += ("attribution",)
    fields = _require_fields(definition, required)
    components = [
        _common(definition, fields),
        _unsigned(fields["order_reference"], 8, "order_reference"),
        _alpha(fields["side"], 1, "side"),
        _unsigned(fields["shares"], 4, "shares"),
        _alpha(fields["stock"], 8, "stock"),
        _unsigned(fields["price4"], 4, "price4"),
    ]
    if attributed:
        components.append(_alpha(fields["attribution"], 4, "attribution"))
    return b"".join(components)


def _encode_order_executed(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "order_reference",
            "executed_shares",
            "match_number",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _unsigned(fields["order_reference"], 8, "order_reference"),
            _unsigned(fields["executed_shares"], 4, "executed_shares"),
            _unsigned(fields["match_number"], 8, "match_number"),
        )
    )


def _encode_order_executed_with_price(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "order_reference",
            "executed_shares",
            "match_number",
            "printable",
            "execution_price4",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _unsigned(fields["order_reference"], 8, "order_reference"),
            _unsigned(fields["executed_shares"], 4, "executed_shares"),
            _unsigned(fields["match_number"], 8, "match_number"),
            _alpha(fields["printable"], 1, "printable"),
            _unsigned(fields["execution_price4"], 4, "execution_price4"),
        )
    )


def _encode_order_cancel(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "order_reference",
            "cancelled_shares",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _unsigned(fields["order_reference"], 8, "order_reference"),
            _unsigned(fields["cancelled_shares"], 4, "cancelled_shares"),
        )
    )


def _encode_order_delete(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        ("stock_locate", "tracking_number", "timestamp_ns", "order_reference"),
    )
    return _common(definition, fields) + _unsigned(fields["order_reference"], 8, "order_reference")


def _encode_order_replace(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "original_order_reference",
            "new_order_reference",
            "shares",
            "price4",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _unsigned(fields["original_order_reference"], 8, "original_order_reference"),
            _unsigned(fields["new_order_reference"], 8, "new_order_reference"),
            _unsigned(fields["shares"], 4, "shares"),
            _unsigned(fields["price4"], 4, "price4"),
        )
    )


def _encode_trade(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "order_reference",
            "side",
            "shares",
            "stock",
            "price4",
            "match_number",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _unsigned(fields["order_reference"], 8, "order_reference"),
            _alpha(fields["side"], 1, "side"),
            _unsigned(fields["shares"], 4, "shares"),
            _alpha(fields["stock"], 8, "stock"),
            _unsigned(fields["price4"], 4, "price4"),
            _unsigned(fields["match_number"], 8, "match_number"),
        )
    )


def _encode_cross_trade(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        (
            "stock_locate",
            "tracking_number",
            "timestamp_ns",
            "shares",
            "stock",
            "cross_price4",
            "match_number",
            "cross_type",
        ),
    )
    return b"".join(
        (
            _common(definition, fields),
            _unsigned(fields["shares"], 8, "shares"),
            _alpha(fields["stock"], 8, "stock"),
            _unsigned(fields["cross_price4"], 4, "cross_price4"),
            _unsigned(fields["match_number"], 8, "match_number"),
            _alpha(fields["cross_type"], 1, "cross_type"),
        )
    )


def _encode_broken_trade(definition: MessageDefinition) -> bytes:
    fields = _require_fields(
        definition,
        ("stock_locate", "tracking_number", "timestamp_ns", "match_number"),
    )
    return _common(definition, fields) + _unsigned(fields["match_number"], 8, "match_number")


def encode_payload(definition: MessageDefinition) -> bytes:
    """Encode one definition without using production constants or decoder code."""
    encoders = {
        "S": _encode_system_event,
        "R": _encode_stock_directory,
        "H": _encode_trading_action,
        "A": lambda value: _encode_add_order(value, attributed=False),
        "F": lambda value: _encode_add_order(value, attributed=True),
        "E": _encode_order_executed,
        "C": _encode_order_executed_with_price,
        "X": _encode_order_cancel,
        "D": _encode_order_delete,
        "U": _encode_order_replace,
        "P": _encode_trade,
        "Q": _encode_cross_trade,
        "B": _encode_broken_trade,
    }
    payload = encoders[definition.message_type](definition)
    expected_length = MESSAGE_LENGTHS[definition.message_type]
    if len(payload) != expected_length:
        raise FixtureBuildError(
            f"{definition.name}: encoded {len(payload)} bytes; expected {expected_length}"
        )
    return payload


def frame_payload(payload: bytes) -> bytes:
    """Prefix one valid payload with its two-byte big-endian length."""
    if not payload:
        raise FixtureBuildError("valid frame payload must not be empty")
    if len(payload) > MAX_FRAME_PAYLOAD:
        raise FixtureBuildError(f"valid frame payload exceeds {MAX_FRAME_PAYLOAD} bytes")
    return len(payload).to_bytes(2, byteorder="big") + payload


def build_stream(definitions: tuple[MessageDefinition, ...]) -> BuiltStream:
    """Encode an ordered, non-empty synthetic message stream."""
    if not definitions:
        raise FixtureBuildError("synthetic stream must contain at least one message")

    built_messages: list[BuiltMessage] = []
    framed_parts: list[bytes] = []
    frame_offset = 0
    for message_index, definition in enumerate(definitions):
        payload = encode_payload(definition)
        framed = frame_payload(payload)
        built_messages.append(
            BuiltMessage(
                definition=definition,
                payload=payload,
                message_index=message_index,
                frame_offset=frame_offset,
                payload_offset=frame_offset + 2,
            )
        )
        framed_parts.append(framed)
        frame_offset += len(framed)
    return BuiltStream(tuple(built_messages), b"".join(framed_parts))


def deterministic_gzip(uncompressed: bytes) -> bytes:
    """Return gzip bytes with stable metadata on every supported platform."""
    destination = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=destination, compresslevel=9, mtime=0
    ) as stream:
        stream.write(uncompressed)
    return destination.getvalue()


def frame_with_observed_payload_length(payload: bytes, observed_length: int) -> bytes:
    """Create a safely bounded wrong-length frame for decoder boundary tests."""
    if isinstance(observed_length, bool) or not isinstance(observed_length, int):
        raise FixtureBuildError("observed_length must be an integer")
    if observed_length < 0 or observed_length > MAX_FRAME_PAYLOAD:
        raise FixtureBuildError(f"observed_length must be in [0, {MAX_FRAME_PAYLOAD}]")
    if observed_length <= len(payload):
        mutated_payload = payload[:observed_length]
    else:
        mutated_payload = payload + bytes(observed_length - len(payload))
    return observed_length.to_bytes(2, byteorder="big") + mutated_payload


def zero_length_frame() -> bytes:
    """Return an invalid zero-length outer frame."""
    return b"\x00\x00"


def oversized_frame_prefix() -> bytes:
    """Declare one byte above the project frame cap without allocating a payload."""
    return (MAX_FRAME_PAYLOAD + 1).to_bytes(2, byteorder="big")


def truncated_length_prefix(valid_stream: bytes) -> bytes:
    """Return a one-byte fragment of the first frame prefix."""
    if len(valid_stream) < 2:
        raise FixtureBuildError("valid_stream must contain a frame prefix")
    return valid_stream[:1]


def truncated_payload_frame(payload: bytes) -> bytes:
    """Declare a complete payload but omit its last byte."""
    if len(payload) < 2:
        raise FixtureBuildError("payload must contain at least two bytes")
    return len(payload).to_bytes(2, byteorder="big") + payload[:-1]


def replace_message_type(payload: bytes, replacement: str) -> bytes:
    """Replace the type byte while retaining a safely framed payload length."""
    if not payload:
        raise FixtureBuildError("payload must not be empty")
    encoded = _alpha(replacement, 1, "replacement")
    return encoded + payload[1:]


def truncated_gzip(compressed: bytes) -> bytes:
    """Remove the complete eight-byte gzip trailer."""
    if len(compressed) <= 8:
        raise FixtureBuildError("compressed input must contain a gzip trailer")
    return compressed[:-8]


def corrupt_gzip_checksum(compressed: bytes) -> bytes:
    """Flip one CRC-32 bit while retaining the gzip member size."""
    if len(compressed) <= 8:
        raise FixtureBuildError("compressed input must contain a gzip trailer")
    mutated = bytearray(compressed)
    mutated[-8] ^= 0x01
    return bytes(mutated)


def as_message_type(value: str) -> MessageType:
    """Narrow a checked runtime string for test-data deserialisation."""
    if value not in MESSAGE_TYPES:
        raise FixtureBuildError(f"unsupported message type {value!r}")
    return value


__all__ = [
    "MAX_FRAME_PAYLOAD",
    "MESSAGE_LENGTHS",
    "MESSAGE_TYPES",
    "BuiltMessage",
    "BuiltStream",
    "FieldValue",
    "FixtureBuildError",
    "MessageDefinition",
    "MessageType",
    "as_message_type",
    "build_stream",
    "corrupt_gzip_checksum",
    "deterministic_gzip",
    "encode_payload",
    "frame_payload",
    "frame_with_observed_payload_length",
    "message",
    "oversized_frame_prefix",
    "replace_message_type",
    "truncated_gzip",
    "truncated_length_prefix",
    "truncated_payload_frame",
    "zero_length_frame",
]
